function [ambi_func] = ambiguity_func(ux, uy, P, radarParameter)
% AMBIGUITY_FUNC
% use ambiguity function to set constraint during optimization
% constrain SLL lower than 1/2 main lobe

% full version
% tpn = (0 : radarParameter.N_Tx - 1) * radarParameter.T_pn;
% E = -2*pi /radarParameter.c0 * [2 * radarParameter.f0 * ones(radarParameter.N_pn, 1),...
%                                 2 * radarParameter.f0 * kron(tpn', ones([radarParameter.N_Rx,1])),...
%                                 radarParameter.f0 * P];

% ambi_func = abs((exp(1j*(E * [objectParameter.r0;...
%                              objectParameter.vr;...
%                              0;0;0])))'...
%               * exp(1j*(E * [objectParameter.r0;...
%                              objectParameter.vr;...
%                              ux;uy;sqrt(1 - ux^2 + uy ^2)]))).^2;

% because we decoupled the velocity
E = -2*pi /radarParameter.c0 * radarParameter.f0 * P;           
ambi_func = abs((exp(1j*(E * [0;0])))'...
              * exp(1j*(E * [ux;uy]))).^2;
end