function [myscenario, egoVehicle] = scenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.7 (R2019b) and Automated Driving Toolbox 3.0 (R2019b).
% Generated on: 22-Jan-2020 21:51:35

% Construct a drivingScenario object.
myscenario = drivingScenario;

% Add all road segments
roadCenters = [50, 0; 0, 0];
roadWidth = 8;
road(myscenario, roadCenters, roadWidth);

% Add the ego vehicle
egoVehicle = vehicle(myscenario, ...
    'ClassID', 1, ...
    'Position', [6 -0.3 0]);

% Add the non-ego actors
vehicle(myscenario, ...
    'ClassID', 1, ...
    'Position', [29.5 -1.9 0]);





